#!/bin/sh

# Seed the Oracle DB with an IDENTITY table and 10 rows.

set -e

# The APP_USER created by the oracle-free image (see up.sh). The table has to be
# owned by this user, because it is the schema SymmetricDS captures from.
ORACLE_CONN="ora/ora@//localhost:1521/FREEPDB1"

kubectl exec -i oracle-db -- sqlplus -S -L "$ORACLE_CONN" <<'SQL'
-- Make sqlplus return a non-zero exit code so `set -e` actually catches failures.
WHENEVER SQLERROR EXIT FAILURE

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE identity PURGE';
  EXECUTE IMMEDIATE 'DROP TABLE id_document_type PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL; -- table did not exist yet
END;
/

CREATE TABLE identity (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL,
  last_name  VARCHAR2(50) NOT NULL,
  birth_date DATE         NOT NULL
);

create table id_document_type (
  id NUMBER(5) not null,
  code VARCHAR2(20) not null,
  label_fr VARCHAR2(100) not null,
  label_en VARCHAR2(100) not null
);

INSERT INTO identity (first_name, last_name, birth_date) values ('Marie', 'Curie', DATE '1867-11-07');
INSERT INTO identity (first_name, last_name, birth_date) values ('Alan', 'Turing', DATE '1912-06-23');
INSERT INTO identity (first_name, last_name, birth_date) values ('Ada', 'Lovelace', DATE '1815-12-10');
INSERT INTO identity (first_name, last_name, birth_date) values ('Louis', 'Pasteur', DATE '1822-12-27');
INSERT INTO identity (first_name, last_name, birth_date) values ('Rosalind', 'Franklin', DATE '1920-07-25');
INSERT INTO identity (first_name, last_name, birth_date) values ('Henri', 'Poincare', DATE '1854-04-29');
INSERT INTO identity (first_name, last_name, birth_date) values ('Grace', 'Hopper', DATE '1906-12-09');
INSERT INTO identity (first_name, last_name, birth_date) values ('Niels', 'Bohr', DATE '1885-10-07');
INSERT INTO identity (first_name, last_name, birth_date) values ('Emmy', 'Noether', DATE '1882-03-23');
INSERT INTO identity (first_name, last_name, birth_date) values ('Blaise', 'Pascal', DATE '1623-06-19');

INSERT INTO id_document_type (id, code, label_fr, label_en) values (1, 'CNI', 'Carte nationale d''identité', 'National identity card');
INSERT INTO id_document_type (id, code, label_fr, label_en) values (2, 'PASSPORT', 'Passport', 'Passport');
INSERT INTO id_document_type (id, code, label_fr, label_en) values (3, 'VISA', 'Visa', 'Visa');

COMMIT;

EXIT
SQL

