#!/bin/sh

# Seed the Oracle DB: the IDENTITY and ID_DOCUMENT_TYPE tables with a handful of
# rows each, and FR_CITIES bulk-loaded from data/fr_cities.csv with SQL*Loader.

set -e

# The APP_USER created by the oracle-free image (see up.sh). The table has to be
# owned by this user, because it is the schema SymmetricDS captures from.
ORACLE_CONN="ora/ora@//localhost:1521/FREEPDB1"

kubectl exec -i oracle-db -- sqlplus -S -L "$ORACLE_CONN" <<'SQL'
-- Make sqlplus return a non-zero exit code so `set -e` actually catches failures.
WHENEVER SQLERROR EXIT FAILURE

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE identity PURGE';
  EXECUTE IMMEDIATE 'DROP TABLE id_document_type PURGE';
  EXECUTE IMMEDIATE 'DROP TABLE fr_cities PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL; -- table did not exist yet
END;
/

CREATE TABLE identity (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL,
  last_name  VARCHAR2(50) NOT NULL,
  birth_date DATE         NOT NULL
);

create table id_document_type (
  id NUMBER(5) not null,
  code VARCHAR2(20) not null,
  label_fr VARCHAR2(100) not null,
  label_en VARCHAR2(100) not null
);

CREATE TABLE fr_cities (
  id           NUMBER(12)          PRIMARY KEY,
  region_code  VARCHAR2(10 CHAR),
  dept_code    VARCHAR2(10 CHAR),
  arrond_code  VARCHAR2(10 CHAR),
  insee_code   VARCHAR2(10 CHAR),
  alt_names    VARCHAR2(2000 CHAR),
  name_ascii   VARCHAR2(200 CHAR),
  country_code VARCHAR2(2 CHAR),
  geoname_id   NUMBER(12),
  latitude     NUMBER(9,6),
  longitude    NUMBER(9,6),
  name         VARCHAR2(200 CHAR),
  population   NUMBER(10)
);

INSERT INTO identity (first_name, last_name, birth_date) values ('Marie', 'Curie', DATE '1867-11-07');
INSERT INTO identity (first_name, last_name, birth_date) values ('Alan', 'Turing', DATE '1912-06-23');
INSERT INTO identity (first_name, last_name, birth_date) values ('Ada', 'Lovelace', DATE '1815-12-10');
INSERT INTO identity (first_name, last_name, birth_date) values ('Louis', 'Pasteur', DATE '1822-12-27');
INSERT INTO identity (first_name, last_name, birth_date) values ('Rosalind', 'Franklin', DATE '1920-07-25');
INSERT INTO identity (first_name, last_name, birth_date) values ('Henri', 'Poincare', DATE '1854-04-29');
INSERT INTO identity (first_name, last_name, birth_date) values ('Grace', 'Hopper', DATE '1906-12-09');
INSERT INTO identity (first_name, last_name, birth_date) values ('Niels', 'Bohr', DATE '1885-10-07');
INSERT INTO identity (first_name, last_name, birth_date) values ('Emmy', 'Noether', DATE '1882-03-23');
INSERT INTO identity (first_name, last_name, birth_date) values ('Blaise', 'Pascal', DATE '1623-06-19');

INSERT INTO id_document_type (id, code, label_fr, label_en) values (1, 'CNI', 'Carte nationale d''identité', 'National identity card');
INSERT INTO id_document_type (id, code, label_fr, label_en) values (2, 'PASSPORT', 'Passport', 'Passport');
INSERT INTO id_document_type (id, code, label_fr, label_en) values (3, 'VISA', 'Visa', 'Visa');

COMMIT;

EXIT
SQL

echo "Start to load cities data (82k rows)..."

kubectl cp data/fr_cities.csv oracle-db:/tmp/fr_cities.csv

kubectl exec -i oracle-db -- sh -c 'cat > /tmp/fr_cities.ctl' <<'CTL'
OPTIONS (ERRORS=0, ROWS=10000, BINDSIZE=33554432, READSIZE=33554432, SILENT=(HEADER,FEEDBACK))
LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/tmp/fr_cities.csv'
BADFILE '/tmp/fr_cities.bad'
TRUNCATE
INTO TABLE fr_cities
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
(
  id INTEGER EXTERNAL, region_code CHAR(10), dept_code CHAR(10),
  arrond_code CHAR(10), insee_code CHAR(10), alt_names CHAR(2000),
  name_ascii CHAR(200), country_code CHAR(2), geoname_id INTEGER EXTERNAL,
  latitude DECIMAL EXTERNAL, longitude DECIMAL EXTERNAL, name CHAR(200),
  population INTEGER EXTERNAL, ignored FILLER CHAR
)
CTL

if ! kubectl exec -i oracle-db -- env NLS_NUMERIC_CHARACTERS='.,' \
     sqlldr userid="$ORACLE_CONN" control=/tmp/fr_cities.ctl log=/tmp/fr_cities.log; then
  echo "sqlldr failed:" >&2
  kubectl exec -i oracle-db -- cat /tmp/fr_cities.log >&2 || true
  exit 1
fi

echo "Cities data loaded..."
