apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres-db
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:15

  storage:
    size: 1Gi
    storageClass: csi-rbd-sc

  bootstrap:
    initdb:
      database: identity
      owner: identity

  enableSuperuserAccess: true
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres-cluster-db-rw-lb
            spec:
              type: LoadBalancer
