apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-pg-engine-config
  namespace: default
data:
  identity-001.properties: |
    engine.name=identity-001

    db.driver=org.postgresql.Driver
    db.url=jdbc:postgresql://identity-pg-rw:5432/identity?currentSchema=symds_identity&stringtype=unspecified
    db.user=identity
    db.password=identity
    db.validation.query=select 1

    registration.url=http://symds-oracle:31415/sync/oracle-000
    sync.url=http://symds-identity:31415/sync/identity-001
    group.id=identity
    external.id=001

    # How to run routing (in millis), which puts changes into batches.
    job.routing.period.time.ms=5000

    # How often to run push (in millis), which sends changes to other nodes.
    job.push.period.time.ms=10000

    #How often to run pull (in millis), which receives changes from other nodes.
    job.pull.period.time.ms=10000

    # Automatically register new nodes when they request it.
    # If this is false, accept the registration requests using "symadmin open-registration" command.
    auto.registration=true
    auto.reload=true

